name: Trigger Sync on iamjoel/dialogue-view-service

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger iamjoel/dialogue-view-service Workflow
      run: |
        curl -X POST \
        -H "Accept: application/vnd.github.everest-preview+json" \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/repos/iamjoel/dialogue-view-service/dispatches \
        -d '{"event_type":"sync_request"}'